package com.hermanli.careerpilot.interview;

public enum InterviewOutputRejectionCategory {
    INVALID_JSON_STRUCTURE,
    UNKNOWN_OR_NON_EXACT_EVIDENCE,
    MISSING_REQUIRED_TYPE,
    DUPLICATE_QUESTION,
    GAP_AS_CLAIMED_EXPERIENCE,
    BEHAVIORAL_SCENARIO_NOT_EVIDENCE_SAFE,
    UNSUPPORTED_TOOL,
    UNSUPPORTED_METRIC,
    ANSWER_OR_HYPOTHETICAL_CONTENT
}
