CREATE TABLE app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(320) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_app_user_email_normalized
        CHECK (email = lower(btrim(email)) AND email <> ''),
    CONSTRAINT ck_app_user_password_hash_not_blank
        CHECK (btrim(password_hash) <> ''),
    CONSTRAINT ck_app_user_status
        CHECK (status IN ('ACTIVE', 'DISABLED'))
);

CREATE UNIQUE INDEX ux_app_user_normalized_email
    ON app_user (lower(btrim(email)));

CREATE TABLE user_profile (
    user_id BIGINT PRIMARY KEY,
    target_role VARCHAR(120),
    target_location VARCHAR(120),
    work_authorization VARCHAR(160),
    weekly_hours SMALLINT,
    education_summary TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user_profile_user
        FOREIGN KEY (user_id) REFERENCES app_user (id),
    CONSTRAINT ck_user_profile_weekly_hours
        CHECK (weekly_hours IS NULL OR weekly_hours BETWEEN 1 AND 168)
);
