CREATE TABLE resume (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    title VARCHAR(160) NOT NULL,
    raw_text TEXT NOT NULL,
    parsed_json JSONB,
    parse_status VARCHAR(30) NOT NULL DEFAULT 'NOT_STARTED',
    parse_error VARCHAR(500),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_resume_user
        FOREIGN KEY (user_id) REFERENCES app_user (id),
    CONSTRAINT ck_resume_title_not_blank
        CHECK (btrim(title) <> ''),
    CONSTRAINT ck_resume_raw_text_not_blank
        CHECK (btrim(raw_text) <> ''),
    CONSTRAINT ck_resume_parse_status
        CHECK (parse_status IN ('NOT_STARTED', 'RUNNING', 'COMPLETED', 'FAILED'))
);

CREATE INDEX ix_resume_user_created_at
    ON resume (user_id, created_at);

CREATE TABLE job_description (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    title VARCHAR(160) NOT NULL,
    company_name VARCHAR(160),
    role_title VARCHAR(160),
    raw_text TEXT NOT NULL,
    parsed_json JSONB,
    parse_status VARCHAR(30) NOT NULL DEFAULT 'NOT_STARTED',
    parse_error VARCHAR(500),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_job_description_user
        FOREIGN KEY (user_id) REFERENCES app_user (id),
    CONSTRAINT ck_job_description_title_not_blank
        CHECK (btrim(title) <> ''),
    CONSTRAINT ck_job_description_raw_text_not_blank
        CHECK (btrim(raw_text) <> ''),
    CONSTRAINT ck_job_description_parse_status
        CHECK (parse_status IN ('NOT_STARTED', 'RUNNING', 'COMPLETED', 'FAILED'))
);

CREATE INDEX ix_job_description_user_created_at
    ON job_description (user_id, created_at);
