CREATE TABLE analysis_report (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    resume_id BIGINT NOT NULL,
    job_description_id BIGINT NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    match_score SMALLINT,
    report_json JSONB,
    question_context_json JSONB,
    model_name VARCHAR(100),
    error_code VARCHAR(80),
    error_message VARCHAR(500),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_analysis_report_user
        FOREIGN KEY (user_id) REFERENCES app_user (id),
    CONSTRAINT fk_analysis_report_resume
        FOREIGN KEY (resume_id) REFERENCES resume (id),
    CONSTRAINT fk_analysis_report_job_description
        FOREIGN KEY (job_description_id) REFERENCES job_description (id),
    CONSTRAINT ck_analysis_report_status
        CHECK (status IN ('PENDING', 'RUNNING', 'WAITING_FOR_USER_INPUT', 'COMPLETED', 'FAILED')),
    CONSTRAINT ck_analysis_report_match_score_range
        CHECK (match_score BETWEEN 0 AND 100)
);

CREATE INDEX ix_analysis_report_user_status_created_at
    ON analysis_report (user_id, status, created_at);
