CREATE TABLE career_plan (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    analysis_report_id BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    summary TEXT NOT NULL,
    duration_days SMALLINT NOT NULL DEFAULT 14,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_career_plan_user
        FOREIGN KEY (user_id) REFERENCES app_user (id),
    CONSTRAINT fk_career_plan_analysis_report
        FOREIGN KEY (analysis_report_id) REFERENCES analysis_report (id),
    CONSTRAINT uq_career_plan_analysis_report
        UNIQUE (analysis_report_id),
    CONSTRAINT ck_career_plan_title_not_blank
        CHECK (btrim(title) <> ''),
    CONSTRAINT ck_career_plan_summary_not_blank
        CHECK (btrim(summary) <> ''),
    CONSTRAINT ck_career_plan_duration_days_positive
        CHECK (duration_days > 0),
    CONSTRAINT ck_career_plan_status
        CHECK (status IN ('ACTIVE', 'COMPLETED', 'ARCHIVED'))
);

CREATE TABLE plan_task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    career_plan_id BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    description TEXT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'TODO',
    due_date DATE NOT NULL,
    priority VARCHAR(20) NOT NULL,
    source_evidence TEXT NOT NULL,
    completed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_plan_task_career_plan
        FOREIGN KEY (career_plan_id) REFERENCES career_plan (id),
    CONSTRAINT ck_plan_task_title_not_blank
        CHECK (btrim(title) <> ''),
    CONSTRAINT ck_plan_task_description_not_blank
        CHECK (btrim(description) <> ''),
    CONSTRAINT ck_plan_task_status
        CHECK (status IN ('TODO', 'IN_PROGRESS', 'COMPLETED', 'SKIPPED')),
    CONSTRAINT ck_plan_task_priority
        CHECK (priority IN ('LOW', 'MEDIUM', 'HIGH')),
    CONSTRAINT ck_plan_task_source_evidence_not_blank
        CHECK (btrim(source_evidence) <> '')
);

CREATE INDEX ix_plan_task_career_plan_due_date
    ON plan_task (career_plan_id, due_date);
