CREATE TABLE interview_session (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    analysis_report_id BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_interview_session_user
        FOREIGN KEY (user_id) REFERENCES app_user (id),
    CONSTRAINT fk_interview_session_analysis_report
        FOREIGN KEY (analysis_report_id) REFERENCES analysis_report (id),
    CONSTRAINT uq_interview_session_analysis_report
        UNIQUE (analysis_report_id),
    CONSTRAINT ck_interview_session_title_not_blank
        CHECK (btrim(title) <> '')
);

CREATE INDEX ix_interview_session_user_created_at
    ON interview_session (user_id, created_at);

CREATE TABLE interview_question (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    interview_session_id BIGINT NOT NULL,
    question_order SMALLINT NOT NULL,
    question_type VARCHAR(30) NOT NULL,
    question_text TEXT NOT NULL,
    assessment_goal TEXT NOT NULL,
    source_evidence TEXT NOT NULL,
    preparation_tip TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_interview_question_session
        FOREIGN KEY (interview_session_id) REFERENCES interview_session (id),
    CONSTRAINT uq_interview_question_session_order
        UNIQUE (interview_session_id, question_order),
    CONSTRAINT ck_interview_question_order
        CHECK (question_order BETWEEN 1 AND 8),
    CONSTRAINT ck_interview_question_type
        CHECK (question_type IN ('TECHNICAL_GAP', 'PROJECT_FOLLOW_UP', 'BEHAVIORAL_EVIDENCE')),
    CONSTRAINT ck_interview_question_text_not_blank
        CHECK (btrim(question_text) <> ''),
    CONSTRAINT ck_interview_question_goal_not_blank
        CHECK (btrim(assessment_goal) <> ''),
    CONSTRAINT ck_interview_question_evidence_not_blank
        CHECK (btrim(source_evidence) <> ''),
    CONSTRAINT ck_interview_question_tip_not_blank
        CHECK (btrim(preparation_tip) <> '')
);

CREATE INDEX ix_interview_question_session_order
    ON interview_question (interview_session_id, question_order);
